# Generated by Django 4.1.7 on 2023-03-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(default='', max_length=200)),
                ('product_desc', models.TextField(default='', max_length=5000)),
                ('product_img', models.ImageField(upload_to='product_img/')),
                ('product_gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('product_category', models.TextField(default='', max_length=100)),
                ('product_subcategory', models.TextField(default='', max_length=100)),
                ('product_price', models.IntegerField(default=0)),
            ],
        ),
    ]
