# Generated by Django 4.1.7 on 2023-03-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0002_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
