# Generated by Django 4.1.7 on 2023-03-18 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0004_contactdata_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('reviewer_name', models.TextField(default='', max_length=200)),
                ('review_desc', models.TextField(default='', max_length=5000)),
                ('date', models.DateField(default=datetime.date.today)),
                ('review_star', models.IntegerField(default=0)),
            ],
        ),
    ]
