# Generated by Django 4.1.7 on 2023-03-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0006_orderitem_order_date_orderitem_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='product_size',
            field=models.TextField(default='', max_length=100),
        ),
    ]
