# Generated by Django 4.1.7 on 2023-03-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0007_productdata_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='product_size',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_size',
            field=models.TextField(default='', max_length=10),
        ),
    ]
