# Generated by Django 4.1.7 on 2023-03-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0008_cartitems_product_size_orderitem_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='product_size',
            field=models.TextField(default='', max_length=100),
        ),
    ]
