# Generated by Django 4.1.7 on 2023-03-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0009_alter_cartitems_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='username',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='username',
            field=models.TextField(default='', max_length=100),
        ),
    ]
