# Generated by Django 4.1.7 on 2023-03-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0010_cartitems_username_orderitem_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='username',
            new_name='full_name',
        ),
    ]
