# Generated by Django 4.1.7 on 2023-03-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0011_rename_username_cartitems_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='username',
            new_name='full_name',
        ),
    ]
