# Generated by Django 4.1.7 on 2023-03-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0012_rename_username_orderitem_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='product_name',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
